name: prism_engine
description: The underlying game engine for the OpenFantasy project.
version: 1.0.0
repository: https://github.com/Open-Fantasy/Prism

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  socket_io_client: ^3.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
